# -*- coding: utf-8 -*-
PART5_TR = {
    "chat.toolCall.execute.conciseCompleted": "Komut çalıştırıldı",
    "chat.toolCall.submitResult.submitting": "Sonuç gönderiliyor",
    "chat.toolCall.submitResult.submitted": "Sonuç gönderildi",
    "chat.toolCall.submitResult.rejected": "Gönderim reddedildi",
    "chat.toolCall.submitResult.stopped": "Gönderim durduruldu",
    "chat.toolCall.submitResult.resultHeading": "Gönderilen sonuç",
    "chat.toolCall.workflow.writing": "İş akışı yazılıyor",
    "chat.toolCall.workflow.revising": "İş akışı düzenleniyor",
    "chat.toolCall.workflow.draft": "İş akışı taslağı",
    "chat.toolCall.workflow.draftOrdinal": "{ordinal}. taslak",
    "chat.toolCall.workflow.awaitingConfirmation": "İş akışı onayı bekleniyor",
    "chat.toolCall.workflow.amend.writing": "İş akışı düzeltmesi yazılıyor",
    "chat.toolCall.workflow.amend.revising": "Düzeltme düzenleniyor",
    "chat.toolCall.workflow.amend.draft": "Düzeltme taslağı",
    "chat.toolCall.workflow.amend.awaitingConfirmation": "Düzeltme onayı bekleniyor",
    "chat.toolCall.workflow.amend.ran": "İş akışı düzeltmesi",
    "chat.toolCall.workflow.amend.amended": "İş akışı düzeltildi",
    "chat.toolCall.workflow.amend.amends": "Düzeltmeler çalıştırması",
    "chat.toolCall.workflow.amend.scriptUnchanged": "komut dosyası değişmedi",
    "chat.toolCall.workflow.running": "İş akışı doğrulanıyor",
    "chat.toolCall.workflow.ran": "İş akışı",
    "chat.toolCall.workflow.fallbackName": "İş akışı komut dosyası",
    "chat.toolCall.workflow.feedback": "Derleyici geri bildirimi",
    "chat.toolCall.workflow.feedback.lede": "Tip kontrolü geçilemedi, bu nedenle hiçbir şey çalıştırılmadı. Geri bildirim düzenlenip yeniden gönderilmesi için modele iletildi.",
    "chat.toolCall.workflow.feedback.lede.saved": "Kayıtlı iş akışı dosyası tip kontrolünü geçemedi, bu nedenle hiçbir şey çalıştırılmadı. Geri bildirim dosyanın düzeltilmesi veya düzeltilmiş sürümün kaydedilmesi için modele iletildi.",
    "chat.toolCall.workflow.feedback.count": "{count} not",
    "chat.toolCall.workflow.feedback.countOne": "{count} not",
    "chat.toolCall.workflow.feedback.rule": "kural {code}",
    "chat.toolCall.workflow.compiled": "derlendi",
    "chat.toolCall.workflow.toFix": "düzeltilecek {count} yer",
    "chat.toolCall.workflow.notRun": "çalıştırılmadı",
    "chat.toolCall.workflow.truncated": "Bazı tanılama bilgileri atlandı.",
    "chat.toolCall.workflow.noScript": "Hiçbir iş akışı komut dosyası sağlanmadı.",
    "chat.toolCall.workflow.graph.truncated": "Grafik çok büyük — bazı katılımcılar atlandı.",
    "chat.toolCall.workflow.graph.lane.script": "Komut Dosyası",
    "chat.toolCall.workflow.graph.lane.unresolved": "Çözümlenmemiş",
    "chat.toolCall.workflow.graph.lane.anonymous": "Anonim Alt Ajan",
    "chat.toolCall.workflow.graph.lane.anonymousIndexed": "Anonim Alt Ajan {index}",
    "chat.toolCall.workflow.graph.card.tasks": "{count} görev",
    "chat.toolCall.workflow.graph.card.reads": "{count} okuma",
    "chat.toolCall.workflow.graph.status.running": "çalışıyor",
    "chat.toolCall.workflow.graph.status.done": "tamamlandı",
    "chat.toolCall.workflow.graph.status.failed": "başarısız oldu",
    "chat.toolCall.workflow.graph.status.pending": "beklemede",
    "chat.toolCall.workflow.graph.phase.unphased": "Gruplanmamış",
    "chat.toolCall.workflow.graph.phase.workflow": "İş Akışı",
    "chat.toolCall.workflow.timeline.rounds": "{count} kez ziyaret edildi",
    "chat.toolCall.workflow.timeline.openAgent": "{name} dökümünü aç",
    "chat.toolCall.workflow.timeline.openScript": "{phase} aşamasındaki komut dosyası adımlarını aç",
    "chat.toolCall.workflow.timeline.roster.done": "{count} tamamlandı",
    "chat.toolCall.workflow.timeline.roster.running": "{count} çalışıyor",
    "chat.toolCall.workflow.timeline.roster.failed": "{count} başarısız",
    "chat.toolCall.workflow.timeline.roster.pending": "{count} beklemede",
    "chat.toolCall.workflow.timeline.roster.more": "+{count} daha",
    "chat.toolCall.workflow.timeline.roster.moreTitle": "+{count} daha fazla alt ajan — çalıştırma bölmesinde herkesi listeleyin",
    "chat.toolCall.workflow.timeline.roster.door.list": "+{count} daha fazla alt ajan — burada listeleyin",
    "chat.toolCall.workflow.timeline.roster.door.fold": "+{count} daha fazla alt ajan — daralt",
    "chat.toolCall.workflow.timeline.ledge.earlier": "{count} önceki aşama, görünüm dışına kaydırıldı",
    "chat.toolCall.workflow.timeline.ledge.later": "{count} sonraki aşama, görünüm dışına kaydırıldı",
    "chat.toolCall.workflow.timeline.scrollbar": "Zaman çizelgesi kaydırma konumu",
    "chat.toolCall.workflow.card.started": "İş akışı başlatıldı",
    "chat.toolCall.workflow.card.running": "İş akışı çalışıyor",
    "chat.toolCall.workflow.card.completed": "İş akışı tamamlandı",
    "chat.toolCall.workflow.card.errored": "İş akışı hata verdi",
    "chat.toolCall.workflow.card.stopped": "İş akışı durduruldu",
    "chat.toolCall.workflow.card.superseded": "İş akışının yerine yenisi geçti",
    "chat.toolCall.workflow.card.ended": "İş akışı sona erdi",
    "chat.toolCall.workflow.card.steps": "{done}/{total} adım",
    "chat.toolCall.workflow.card.phase": "{count} aşama",
    "chat.toolCall.workflow.card.phases": "{count} aşama",
    "chat.toolCall.workflow.card.agent": "{count} ajan",
    "chat.toolCall.workflow.card.agents": "{count} ajan",
    "chat.toolCall.workflow.card.agentWorking": "{count} ajan çalışıyor",
    "chat.toolCall.workflow.card.agentsWorking": "{count} ajan çalışıyor",
    "chat.toolCall.workflow.card.tokens": "{count} token",
    "chat.toolCall.workflow.card.round": "{count}. tur",
    "chat.toolCall.workflow.card.rounds": "{count} tur",
    "chat.toolCall.workflow.card.artifact": "{count} çıktı",
    "chat.toolCall.workflow.card.artifacts": "{count} çıktı",
    "chat.toolCall.workflow.digest.question": "{count} soru",
    "chat.toolCall.workflow.digest.questions": "{count} soru",
    "chat.toolCall.workflow.digest.showAgents": "Alt ajanları göster",
    "chat.toolCall.workflow.digest.hideAgents": "Alt ajanları gizle",
    "chat.toolCall.workflow.completion.time": "süre",
    "chat.toolCall.workflow.completion.tokens": "token",
    "chat.toolCall.workflow.completion.subagents": "alt ajanlar",
    "chat.toolCall.workflow.completion.phases": "aşamalar",
    "chat.toolCall.workflow.completion.unavailable": "Kullanılamıyor",
    "chat.toolCall.workflow.completion.moreArtifacts": "+{count} daha",
    "chat.toolCall.workflow.run.phase.expand": "{name} aşamasını göster",
    "chat.toolCall.workflow.run.phase.collapse": "{name} aşamasını gizle",
    "chat.toolCall.workflow.save.saving": "İş akışı kaydediliyor",
    "chat.toolCall.workflow.save.saved": "İş akışı kaydedildi",
    "chat.toolCall.workflow.save.overwrite": "üzerine yaz",
    "chat.toolCall.workflow.save.scope.label": "Kapsam",
    "chat.toolCall.workflow.save.scope.project": "Proje",
    "chat.toolCall.workflow.save.scope.global": "Genel — her projeden görülebilir",
    "chat.toolCall.workflow.save.scope.hidesGlobal": "Bu ada sahip bir genel iş akışı bu iş akışı tarafından gizlenecek",
    "chat.toolCall.workflow.save.scope.hiddenByProject": "Bu projede zaten bu ada sahip bir iş akışı var, buradaki bu iş akışını gizleyecek",
    "chat.toolCall.workflow.scope.global": "Genel",
    "chat.toolCall.workflow.list.listing": "Kayıtlı iş akışları listeleniyor",
    "chat.toolCall.workflow.list.listed": "Kayıtlı iş akışları",
    "chat.toolCall.workflow.list.count": "{count} iş akışı",
    "chat.toolCall.workflow.list.countOne": "{count} iş akışı",
    "chat.toolCall.workflow.list.empty": "Bu projede kayıtlı iş akışı yok",
    "chat.toolCall.workflow.list.invalid": "{count} dosya okunamadı",
    "chat.toolCall.workflow.list.invalidOne": "{count} dosya okunamadı",
    "chat.toolCall.workflow.models.listing": "Modeller listeleniyor",
    "chat.toolCall.workflow.models.listed": "Kullanılabilir modeller",
    "chat.toolCall.workflow.models.count": "{count} model",
    "chat.toolCall.workflow.models.countOne": "{count} model",
    "chat.toolCall.workflow.models.empty": "Bu ana makinede yapılandırılmış model yok",
    "chat.toolCall.workflow.models.provider": "Sağlayıcı",
    "chat.toolCall.workflow.models.current": "geçerli",
    "chat.toolCall.workflow.models.levels": "Düşünce seviyeleri: {levels} (varsayılan {default})",
    "chat.toolCall.workflow.models.levelsNoDefault": "Düşünce seviyeleri: {levels}",
    "chat.toolCall.workflow.models.noLevels": "Düşünce seviyesi yok",
    "chat.toolCall.workflow.models.truncated": "Tüm modeller gösterilmiyor",
    "chat.toolCall.workflow.getRun.fetching": "İş akışı durumu denetleniyor",
    "chat.toolCall.workflow.getRun.runningNodes": "{count} çalışan düğüm",
    "chat.toolCall.workflow.getRun.fetched": "İş akışı durumu",
    "chat.toolCall.workflow.getRun.nodesLine": "{observed} düğüm · {done} tamamlandı · {running} çalışıyor · {failed} başarısız",
    "chat.toolCall.workflow.getRun.section.actors": "Alt Ajanlar",
    "chat.toolCall.workflow.getRun.section.logTail": "Günlükler",
    "chat.toolCall.workflow.getRun.section.result": "Sonuç",
    "chat.toolCall.workflow.getRun.section.error": "Hata",
    "chat.toolCall.workflow.getRun.logEmpty": "Henüz günlük yok",
    "chat.toolCall.workflow.getRun.interruptedHint": "Bu oturum bu çalıştırmanın hâlâ etkin olduğunu doğrulayamıyor: kesintiye uğramış olabilir.",
    "chat.toolCall.workflow.getRun.age": "{age} önce",
    "chat.toolCall.workflow.getRun.truncated": "Bazı satırlar bu kartın dışında bırakıldı.",
    "chat.toolCall.workflow.getRun.questionsUnknown": "Bu oturum bu çalıştırmanın bekleyen sorularını göremiyor. Çalıştırmayı sürdürmek, bir alt ajanın hâlâ ihtiyaç duyduğu şeyleri yeniden sorar.",
    "chat.toolCall.workflow.getRun.phase.state.done": "tamamlandı",
    "chat.toolCall.workflow.getRun.phase.state.current": "geçerli",
    "chat.toolCall.workflow.getRun.phase.state.ahead": "ileride",
    "chat.toolCall.workflow.getRun.phase.state.unfinished": "tamamlanmamış",
    "chat.toolCall.workflow.getRun.phase.rounds": "{count} tur",
    "chat.toolCall.workflow.getRun.phase.roundsOne": "{count} tur",
    "chat.toolCall.workflow.getRun.phase.settled": "{count} sonuçlandı",
    "chat.toolCall.workflow.getRun.phase.running": "{count} çalışıyor",
    "chat.toolCall.workflow.getRun.phase.unfinished": "{count} tamamlanmamış",
    "chat.toolCall.workflow.getRun.phase.soFar": "şimdiye kadar {duration}",
    "chat.toolCall.workflow.getRun.subagent.state.idle": "boşta",
    "chat.toolCall.workflow.getRun.subagent.state.executing": "yürütülüyor",
    "chat.toolCall.workflow.getRun.subagent.state.waiting": "bekliyor",
    "chat.toolCall.workflow.getRun.subagent.state.parked": "park edildi",
    "chat.toolCall.workflow.getRun.subagent.state.done": "tamamlandı",
    "chat.toolCall.workflow.getRun.subagent.state.failed": "başarısız oldu",
    "chat.toolCall.workflow.getRun.subagent.state.unfinished": "tamamlanmamış",
    "chat.toolCall.workflow.getRun.subagent.phase": "{name} aşaması",
    "chat.toolCall.workflow.getRun.subagent.parkedOn": "{qid} sorusunda",
    "chat.toolCall.workflow.getRun.subagent.waitingSlot": "yuva bekliyor",
    "chat.toolCall.workflow.getRun.subagent.waitingBackoff": "bekleme aralığında",
    "chat.toolCall.workflow.getRun.subagent.waitedFor": "{age} boyunca",
    "chat.toolCall.workflow.getRun.subagent.retryIn": "{duration} içinde tekrar dene",
    "chat.toolCall.workflow.getRun.subagent.inFlightAtStop": "durdurulduğunda işlemdeydi",
    "chat.toolCall.workflow.getRun.subagent.onStep": "bu adımda {age}",
    "chat.toolCall.workflow.getRun.subagent.turn": "{count}. tur",
    "chat.toolCall.workflow.getRun.subagent.toolCalls": "{count} araç çağrısı",
    "chat.toolCall.workflow.getRun.subagent.toolCallsOne": "{count} araç çağrısı",
    "chat.toolCall.workflow.getRun.subagent.lastTool": "son {name}",
    "chat.toolCall.workflow.getRun.subagent.steps": "{count} adım",
    "chat.toolCall.workflow.getRun.subagent.stepsOne": "{count} adım",
    "chat.toolCall.workflow.getRun.subagent.stepsFailed": "{count} başarısız oldu",
    "chat.toolCall.workflow.getRun.subagent.task": "görev: {task}",
    "chat.toolCall.workflow.getRun.health.lastProgress": "son ilerleme {age} önce",
    "chat.toolCall.workflow.getRun.health.concurrency": "eşzamanlılık {effective}/{cap}",
    "chat.toolCall.workflow.getRun.health.concurrencySince": "{age} önceden beri",
    "chat.toolCall.workflow.getRun.health.stalled": "{age} önceden beri takıldı",
    "chat.toolCall.workflow.getRun.health.stalledNoClock": "takıldı",
    "chat.toolCall.workflow.getRun.health.notStalled": "takılmadı",
    "chat.toolCall.workflow.getRun.health.failures": "art arda {count} hata",
    "chat.toolCall.workflow.getRun.health.failuresOne": "art arda {count} hata",
    "chat.toolCall.workflow.getRun.health.cachedSteps": "{count} önbelleğe alınmış adım",
    "chat.toolCall.workflow.getRun.health.cachedStepsOne": "{count} önbelleğe alınmış adım",
    "chat.toolCall.workflow.getRun.health.leftover": "Aşağıda çalışıyor olarak işaretlenen {count} adım, canlı çalışma değil, sonlandırılmış işlemin kalıntılarıdır.",
    "chat.toolCall.workflow.getRun.health.leftoverOne": "Aşağıda çalışıyor olarak işaretlenen adım, canlı çalışma değil, sonlandırılmış işlemin bir kalıntısıdır.",
    "chat.toolCall.workflow.resumeRun.resuming": "İş akışı çalıştırması sürdürülüyor",
    "chat.toolCall.workflow.resumeRun.label": "İş akışı çalıştırması sürdürüldü",
    "chat.toolCall.workflow.resumeRun.inBackground": "Arka planda çalışıyor",
    "chat.toolCall.workflow.resumeRun.hint": "Çalıştırma aynı çalıştırma kimliği altında devam eder: tamamlanan adımlar günlükten yeniden oynatılır, tamamlanmamış olanlar yeniden gönderilir. Nihai çıktıyı içeren bir tamamlama bildirimi gelecektir.",
    "chat.toolCall.workflow.listRuns.listing": "İş akışı çalıştırmaları listeleniyor",
    "chat.toolCall.workflow.listRuns.listed": "İş akışı çalıştırmaları",
    "chat.toolCall.workflow.listRuns.count": "{count} çalıştırma",
    "chat.toolCall.workflow.listRuns.countOne": "{count} çalıştırma",
    "chat.toolCall.workflow.listRuns.empty": "Henüz iş akışı çalıştırması yok",
    "chat.toolCall.workflow.listRuns.truncated": "Yalnızca en son çalıştırmalar gösteriliyor",
    "chat.toolCall.workflow.listRuns.ownSession": "bu oturum",
    "chat.toolCall.workflow.listRuns.interrupted": "muhtemelen kesintiye uğradı",
    "chat.toolCall.workflow.snippet.validating": "İş akışı kod parçası çalıştırılıyor",
    "chat.toolCall.workflow.snippet.ran": "İş akışı kod parçası"
}
