# -*- coding: utf-8 -*-
PART6_TR = {
    "chat.toolCall.workflow.snippet.passed": "BAŞARILI",
    "chat.toolCall.workflow.snippet.section.code": "Kod",
    "chat.toolCall.workflow.snippet.section.logs": "Günlükler",
    "chat.toolCall.workflow.snippet.section.response": "Dönüş değeri",
    "chat.toolCall.workflow.snippet.logsEmpty": "Günlük yok",
    "chat.toolCall.workflow.escalate.asking": "Ana ajana soruluyor",
    "chat.toolCall.workflow.escalate.asked": "Ana ajana soruldu",
    "chat.toolCall.workflow.escalate.question": "Soru",
    "chat.toolCall.workflow.escalate.context": "Bağlam",
    "chat.toolCall.workflow.escalate.answer": "Yanıt",
    "chat.toolCall.workflow.escalate.fallbackName": "Soru",
    "chat.toolCall.workflow.resolveQuestion.answering": "Soru yanıtlanıyor",
    "chat.toolCall.workflow.resolveQuestion.answered": "Soru yanıtlandı",
    "chat.toolCall.workflow.resolveQuestion.questionId": "Soru Kimliği",
    "chat.toolCall.workflow.resolveQuestion.answer": "Yanıt",
    "chat.toolCall.workflow.resolveQuestion.outcome": "Sonuç",
    "chat.toolCall.workflow.resolveQuestion.fallbackName": "Yanıt",
    "chat.toolCall.workflow.openRunDetails": "Çalıştırma ayrıntılarını aç",
    "chat.toolCall.workflow.run.status.pending": "Beklemede",
    "chat.toolCall.workflow.run.status.running": "Çalışıyor",
    "chat.toolCall.workflow.run.status.completed": "Tamamlandı",
    "chat.toolCall.workflow.run.status.errored": "Hata verdi",
    "chat.toolCall.workflow.run.status.stopped": "Durduruldu",
    "chat.toolCall.workflow.run.stopReason.user": "sizin tarafınızdan",
    "chat.toolCall.workflow.run.stopReason.model": "ajan tarafından",
    "chat.toolCall.workflow.run.stopReason.provider": "model hatası",
    "chat.toolCall.workflow.run.stopReason.interrupted": "işlem sonlandı",
    "chat.toolCall.workflow.run.stopReason.superseded": "yerine başkası geçti",
    "chat.toolCall.workflow.run.resumable": "sürdürülebilir",
    "chat.toolCall.workflow.run.amends": "Düzeltmeler çalıştırması",
    "chat.toolCall.workflow.run.supersededBy": "Yerine geçen çalıştırma",
    "chat.toolCall.workflow.run.outcome.ok": "başarılı",
    "chat.toolCall.workflow.run.outcome.failed": "başarısız",
    "chat.toolCall.workflow.run.outcome.cancelled": "iptal edildi",
    "chat.toolCall.workflow.run.usage.label": "Kullanım",
    "chat.toolCall.workflow.run.usage.tokens": "{tokens} token",
    "chat.toolCall.workflow.run.usage.value": "{tokens} token · {steps} adım",
    "chat.toolCall.workflow.run.cancel": "Çalıştırmayı durdur",
    "chat.toolCall.workflow.run.cancelling": "Durduruluyor…",
    "chat.toolCall.workflow.run.cancelDisabled": "Yalnızca çalışan bir iş akışı durdurulabilir.",
    "chat.toolCall.workflow.run.stopHint": "Daha sonra sürdürebilirsiniz; tamamlanan adımlar saklanır.",
    "chat.toolCall.workflow.run.rejection.cancel.not_found": "Bu çalıştırma bu ajanda çalışmıyor, bu nedenle hiçbir şey durdurulmadı.",
    "chat.toolCall.workflow.run.rejection.cancel.not_running": "Bu çalıştırma zaten sona erdi, bu nedenle hiçbir şey durdurulmadı.",
    "chat.toolCall.workflow.run.rejection.cancel.cancel_not_supported": "Bu çalıştırma buradan durdurulamaz.",
    "chat.toolCall.workflow.run.rejection.cancel.unsupported": "Bu ajan iş akışı çalıştırmalarını durduramaz.",
    "chat.toolCall.workflow.run.rejection.cancel.generic": "Çalıştırma durdurulamadı ({code}).",
    "chat.toolCall.workflow.run.rejection.resume.compile_failed": "Saklanan komut dosyası artık iş akışı ön yüzünün bu sürümüyle derlenmiyor. İş akışını sürdürmek yerine ajandan düzeltmesini isteyin.",
    "chat.toolCall.workflow.run.rejection.resume.not_found": "Bu çalıştırma bu oturumun günlüğünde yer almıyor.",
    "chat.toolCall.workflow.run.rejection.resume.not_resumable": "Yalnızca durdurulmuş bir çalıştırma sürdürülebilir.",
    "chat.toolCall.workflow.run.rejection.resume.superseded": "Düzeltilmiş bir çalıştırma bunun yerini aldı; bunun yerine ardıl çalıştırmayı açın.",
    "chat.toolCall.workflow.run.rejection.resume.already_running": "Bu çalıştırma zaten işlemde.",
    "chat.toolCall.workflow.run.rejection.resume.script_missing": "Bu çalıştırmada yeniden çalıştırılacak saklanmış bir komut dosyası yok.",
    "chat.toolCall.workflow.run.rejection.resume.script_mismatch": "Saklanan komut dosyası artık kayıtlı karmasıyla eşleşmiyor.",
    "chat.toolCall.workflow.run.rejection.resume.unsupported": "Bu ajan iş akışı çalıştırmalarını sürdüremez.",
    "chat.toolCall.workflow.run.rejection.resume.generic": "Çalıştırma sürdürülemedi ({code}).",
    "chat.toolCall.workflow.run.resume": "Çalıştırmayı sürdür",
    "chat.toolCall.workflow.run.resumeHint": "Durduğu yerden devam edin: tamamlanan adımlar yeniden kullanılır, kesintiye uğrayan adımlar tekrar çalışır.",
    "chat.toolCall.workflow.run.configure": "Yapılandır",
    "chat.toolCall.workflow.run.settings.title": "İş akışını yapılandır",
    "chat.toolCall.workflow.run.settings.model": "Alt ajan modeli",
    "chat.toolCall.workflow.run.settings.model.session": "oturum modeli",
    "chat.toolCall.workflow.run.settings.model.sessionFallback": "Oturum modeli",
    "chat.toolCall.workflow.run.settings.model.unavailable": "kullanılamıyor",
    "chat.toolCall.workflow.run.settings.model.noCatalog": "Bu ajanın model kataloğu yok; alt ajanlar oturum modelinde kalır.",
    "chat.toolCall.workflow.run.settings.limit": "Aynı anda en fazla alt ajan",
    "chat.toolCall.workflow.run.settings.limit.ceiling": "bu makine en fazla {n} taneye izin verir",
    "chat.toolCall.workflow.run.settings.limit.atCeiling": "= bu makinenin sınırı",
    "chat.toolCall.workflow.run.settings.limit.decrease": "Aynı anda daha az",
    "chat.toolCall.workflow.run.settings.limit.increase": "Aynı anda daha fazla",
    "chat.toolCall.workflow.run.settings.consequence.running": "Bu çalıştırmayı durdurur ve bu ayarlarla yeni bir çalıştırma başlatır; tamamlanan adımlar korunur.",
    "chat.toolCall.workflow.run.settings.consequence.pending": "Bu ayarlarla yeni bir çalıştırma başlatır; bu henüz hiçbir adıma başlamadı.",
    "chat.toolCall.workflow.run.settings.consequence.stopped": "Bu ayarlarla yeni bir çalıştırma olarak devam eder; tamamlanan adımlar korunur.",
    "chat.toolCall.workflow.run.settings.consequence.errored": "Bu ayarlarla yeni bir çalıştırma olarak yeniden dener; tamamlanan adımlar korunur.",
    "chat.toolCall.workflow.run.settings.apply": "Uygula",
    "chat.toolCall.workflow.run.settings.applying": "Uygulanıyor…",
    "chat.toolCall.workflow.run.settings.rejection.not_found": "Bu çalıştırma bu konuşmanın kayıtlarında yer almıyor.",
    "chat.toolCall.workflow.run.settings.rejection.not_configurable": "Bu çalıştırma artık yapılandırılamaz.",
    "chat.toolCall.workflow.run.settings.rejection.unchanged": "Bunlar çalıştırmanın geçerli ayarlarıdır.",
    "chat.toolCall.workflow.run.settings.rejection.script_missing": "Bu çalıştırmada saklanan bir komut dosyası yok, bu nedenle ayarları buradan değiştirilemez.",
    "chat.toolCall.workflow.run.settings.rejection.model_unavailable": "Bu model şu anda bu ajanda kullanılamıyor.",
    "chat.toolCall.workflow.run.settings.rejection.compile_failed": "Saklanan komut dosyası artık iş akışı ön yüzünün bu sürümüyle derlenmiyor. Ajandan iş akışını düzeltmesini isteyin.",
    "chat.toolCall.workflow.run.settings.rejection.missing_boundaries": "Bu çalıştırmanın kayıtları tamamlanan çalışmasını devretmek için çok eski.",
    "chat.toolCall.workflow.run.settings.rejection.start_failed": "Yeni çalıştırma başlatılamadı ({message}).",
    "chat.toolCall.workflow.run.settings.rejection.unsupported": "Bu ajan iş akışı ayarlarını buradan değiştiremez.",
    "chat.toolCall.workflow.run.settings.rejection.generic": "Ayarlar değiştirilemedi ({code}).",
    "chat.toolCall.workflow.settingsChange.kind": "Ayarlar değiştirildi",
    "chat.toolCall.workflow.settingsChange.model": "alt ajanlar {model} üzerinde",
    "chat.toolCall.workflow.settingsChange.modelSession": "alt ajanlar yeniden oturum modelinde",
    "chat.toolCall.workflow.settingsChange.limit": "aynı anda en fazla {n}",
    "chat.toolCall.workflow.settingsChange.limitCeiling": "sınır bu makinenin varsayılanına döndürüldü",
    "chat.toolCall.workflow.run.result.title": "Sonuç",
    "chat.toolCall.workflow.run.result.completedHint": "Bu çalıştırma bitti. Sonucu bir arka plan sonuç mesajı olarak sohbete iletildi.",
    "chat.toolCall.workflow.run.result.erroredTitle": "Çalıştırma hata verdi",
    "chat.toolCall.workflow.run.result.stoppedTitle": "Çalıştırma durduruldu",
    "chat.toolCall.workflow.run.result.noError": "Hiçbir hata ayrıntısı kaydedilmedi.",
    "chat.toolCall.workflow.run.artifacts.title": "Çıktılar",
    "chat.toolCall.workflow.run.artifacts.expand": "Çıktıları göster",
    "chat.toolCall.workflow.run.artifacts.collapse": "Çıktıları gizle",
    "chat.toolCall.workflow.run.artifacts.kind.file": "Dosya",
    "chat.toolCall.workflow.run.artifacts.kind.markdown": "Belge",
    "chat.toolCall.workflow.run.artifacts.kind.chart": "Grafik",
    "chat.toolCall.workflow.run.artifacts.kind.table": "Tablo",
    "chat.toolCall.workflow.run.artifacts.kind.metrics": "Metrikler",
    "chat.toolCall.workflow.run.artifacts.kind.board": "Pano",
    "chat.toolCall.workflow.run.artifacts.version": "v{version}",
    "chat.toolCall.workflow.run.artifacts.versionTail": "v{version}",
    "chat.toolCall.workflow.run.artifacts.versionOf": "v{version} / {total}",
    "chat.toolCall.workflow.run.artifacts.previousVersion": "Önceki sürüm",
    "chat.toolCall.workflow.run.artifacts.nextVersion": "Sonraki sürüm",
    "chat.toolCall.workflow.run.artifacts.open": "Çıktıyı aç",
    "chat.toolCall.workflow.run.artifacts.reveal": "Çalışma alanında göster",
    "chat.toolCall.workflow.run.artifacts.copy": "Kopyala",
    "chat.toolCall.workflow.run.artifacts.copied": "Kopyalandı",
    "chat.toolCall.workflow.run.artifacts.openInBrowser": "Tarayıcıda aç",
    "chat.toolCall.workflow.run.artifacts.openInBrowserNote": "Bu sürüme sabitlenen baytları değil, çalışma alanınızdaki kopyayı açar.",
    "chat.toolCall.workflow.run.artifacts.localOnly": "Önizleme yalnızca yerel bir çalışma alanında kullanılabilir.",
    "chat.toolCall.workflow.run.artifacts.loading": "Çıktı yükleniyor…",
    "chat.toolCall.workflow.run.artifacts.missing": "Bu çıktı artık kullanılamıyor.",
    "chat.toolCall.workflow.run.artifacts.loadError": "Bu çıktı yüklenemedi.",
    "chat.toolCall.workflow.run.artifacts.unsupported": "Bu dosya türü için önizleme yok. Çalışma alanında kullanılabilir kalır.",
    "chat.toolCall.workflow.run.artifacts.presetInvalid": "Bu gösterge paneli tanımı oluşturulamıyor.",
    "chat.toolCall.workflow.run.artifacts.unavailable": "Bu sohbet için çıktı ayrıntıları mevcut değil.",
    "chat.toolCall.workflow.run.artifacts.preset.otherColumn": "Diğer",
    "chat.toolCall.workflow.run.artifacts.preset.empty": "Henüz veri yok",
    "chat.toolCall.workflow.run.artifacts.preset.items": "{count} öge",
    "chat.toolCall.workflow.run.questions.title": "Bir yanıt bekleniyor",
    "chat.toolCall.workflow.run.graph.unavailable": "İş akışı grafiği bu konuşmanın görünür geçmişinde değil.",
    "chat.toolCall.workflow.run.untracked.title": "Artık canlı izlenmiyor",
    "chat.toolCall.workflow.run.untracked.body": "Bu çalıştırma, canlı durum için saklanan en son çalıştırmaların dışındadır. Kaydı hâlâ eksiksizdir.",
    "chat.toolCall.workflow.script.title": "Komut Dosyası",
    "chat.toolCall.workflow.script.notStarted.title": "Komut dosyası henüz hiçbir şey çalıştırmadı",
    "chat.toolCall.workflow.script.notStarted.body": "Okumalar, aramalar ve komutlar, komut dosyası projeye dokunduğu anda burada görünür.",
    "chat.toolCall.workflow.script.summary.phases": "{count} aşama",
    "chat.toolCall.workflow.script.summary.phases.one": "1 aşama",
    "chat.toolCall.workflow.script.summary.steps": "{count} adım",
    "chat.toolCall.workflow.script.summary.steps.one": "1 adım",
    "chat.toolCall.workflow.script.verb.read": "Okundu",
    "chat.toolCall.workflow.script.verb.searched": "Arandı",
    "chat.toolCall.workflow.script.search.in": "konumunda",
    "chat.toolCall.workflow.script.startedAgo": "{ago} önce başladı",
    "chat.toolCall.workflow.script.now": "şimdi",
    "chat.toolCall.workflow.script.result.more": "+{count} daha",
    "chat.toolCall.workflow.script.unavailable": "Bu oturum komut dosyasının adımlarını gösteremiyor. Bunları okumak için CLI'yi güncelleyin.",
    "chat.toolCall.workflow.script.loadFailed": "Komut dosyasının adımları yüklenemedi: {error}",
    "chat.toolCall.workflow.script.listTruncated": "Yalnızca ilk {count} adım gösteriliyor.",
    "chat.toolCall.workflow.script.kind.step": "Adım",
    "chat.toolCall.workflow.script.status.exit": "çıkış {code}",
    "chat.toolCall.workflow.script.status.timedOut": "zaman aşımına uğradı",
    "chat.toolCall.workflow.script.status.replayed": "yeniden oynatıldı",
    "chat.toolCall.workflow.script.status.replayedHint": "Daha önceki bir çalıştırmanın günlüğünden yeniden oynatıldı; komut tekrar çalıştırılmadı.",
    "chat.toolCall.workflow.script.result.files": "{count} dosya",
    "chat.toolCall.workflow.script.result.matches": "{count} eşleşme",
    "chat.toolCall.workflow.script.result.lines": "{count} satır",
    "chat.toolCall.workflow.script.result.empty": "Hiçbir şey eşleşmedi.",
    "chat.toolCall.workflow.script.result.loading": "Yükleniyor…",
    "chat.toolCall.workflow.script.result.loadFailed": "Sonuç yüklenemedi: {error}",
    "chat.toolCall.workflow.script.result.truncated": "Toplam {total} sonucun ilk {shown} tanesi gösteriliyor; tam sonuç günlükte kalır.",
    "chat.toolCall.workflow.script.result.stderr": "standart hata",
    "chat.toolCall.workflow.script.args.truncated": "Bağımsız değişkenler günlüğe kaydedilmeden önce kısaltıldı.",
    "chat.toolCall.workflow.run.actor.notStarted.title": "Henüz başlamadı",
    "chat.toolCall.workflow.run.actor.notStarted.body": "Bu alt ajana henüz hiçbir şey sorulmadı. İlk adımı gönderilir gönderilmez döküm burada görünür.",
    "chat.toolCall.workflow.run.event.runStarted": "Çalıştırma başladı",
    "chat.toolCall.workflow.run.event.actorCreated": "Alt ajan oluşturuldu",
    "chat.toolCall.workflow.run.event.nodeQueued": "Kuyruğa alındı",
    "chat.toolCall.workflow.run.event.nodeDispatched": "Gönderildi",
    "chat.toolCall.workflow.run.event.nodeRepairing": "Onarılıyor ({attempt}. deneme)",
    "chat.toolCall.workflow.run.event.nodeNudged": "Tetiklendi",
    "chat.toolCall.workflow.run.event.nodeSettled": "Sonuçlandı · {outcome}",
    "chat.toolCall.workflow.run.event.nodeSettledCached": "Sonuçlandı · {outcome} (önbellekten)",
    "chat.toolCall.workflow.run.event.usageUpdated": "Kullanım güncellendi",
    "chat.toolCall.workflow.run.event.log": "Günlük",
    "chat.toolCall.workflow.run.event.importCacheClosed": "Çalışma alanı yazma işlemiyle önbellek kapatıldı",
    "chat.toolCall.workflow.run.event.report": "Bildirildi",
    "chat.toolCall.workflow.run.event.phaseEntered": "Aşamaya girildi",
    "chat.toolCall.workflow.run.event.escalationRaised": "Ana ajana soruldu",
    "chat.toolCall.workflow.run.event.escalationResolved": "Yanıtlandı",
    "chat.toolCall.workflow.run.event.runSettled": "Çalıştırma sonuçlandı · {status}",
    "chat.toolCall.workflow.run.event.unknown": "{type}",
    "chat.toolCall.workflow.run.event.nodeWaitingSlot": "Yuva bekleniyor",
    "chat.toolCall.workflow.run.event.nodeWaitingBackoff": "Sağlayıcı bekleniyor ({reason}) · {seconds}sn içinde tekrar dene",
    "chat.toolCall.workflow.run.event.nodeExecuting": "İstek gönderildi",
    "chat.toolCall.workflow.run.event.concurrencyChanged": "Eşzamanlılık {previous} → {next}",
    "chat.toolCall.workflow.run.throttle.reason.rateLimited": "istek hızı sınırlandı",
    "chat.toolCall.workflow.run.throttle.reason.overloaded": "aşırı yüklendi",
    "chat.toolCall.workflow.run.throttle.reason.offpeak": "yoğun olmayan saat kuyruğu",
    "chat.toolCall.workflow.run.throttle.reason.transient": "geçici hata",
    "chat.toolCall.workflow.run.concurrency.label": "Eşzamanlılık {cap}",
    "chat.toolCall.workflow.run.concurrency.cooldown": "{time} zamanına kadar soğuma süresi",
    "chat.toolCall.workflow.run.subagentModel.label": "Alt ajanlar {model}",
    "chat.toolCall.workflow.subagentModel.withLevel": "{model} · düşünce {level}",
    "chat.toolCall.workflow.subagentModel.tooltip": "Alt ajanlar {model} üzerinde çalışır. Ana ajan oturum modelinde kalır."
}
