# -*- coding: utf-8 -*-
"""
v314_part2_settings.py
settings (81 keys) translations
"""

PART2_TR = {
    "settings.interfaceMode": "Arayüz modu",
    "settings.interfaceMode.office": "Ofis modu",
    "settings.interfaceMode.coding": "Kodlama modu",
    "settings.interfaceMode.description": "Ofis modu özetlere ve sonuçlara odaklanır. Kodlama modu komutları, çıktıları ve kod değişikliklerini gösterir.",
    "settings.shortcuts.title": "Klavye Kısayolları",
    "settings.shortcuts.searchPlaceholder": "Kısayollarda ara",
    "settings.shortcuts.keySearchAria": "Tuş kombinasyonuyla ara",
    "settings.shortcuts.keySearchPlaceholder": "Aramak için bir tuş kombinasyonuna basın…",
    "settings.shortcuts.keySearchClearAria": "Tuş aramasını temizle",
    "settings.shortcuts.keySearchEmpty": "{keys} için atanmış bir komut yok",
    "settings.shortcuts.searchEmpty": "Eşleşen komut bulunamadı",
    "settings.shortcuts.resetAll": "Tümünü varsayılana sıfırla",
    "settings.shortcuts.resetAllConfirmTitle": "Tüm kısayollar varsayılana sıfırlansın mı?",
    "settings.shortcuts.resetAllConfirmDescription": "Bu işlem tüm özel tuş atamalarını temizler ve her komutu varsayılan atamasına döndürür.",
    "settings.shortcuts.columnHeaderCommand": "Komut",
    "settings.shortcuts.columnHeaderBinding": "Tuş Ataması",
    "settings.shortcuts.columnHeaderActions": "İşlemler",
    "settings.shortcuts.columnHeaderScope": "Kapsam",
    "settings.shortcuts.notSet": "Atanmamış",
    "settings.shortcuts.desktopOnly": "Yalnızca masaüstü",
    "settings.shortcuts.scopeComposer": "Düzenleyici",
    "settings.shortcuts.scopeGlobal": "Genel",
    "settings.shortcuts.recording": "Yeni kombinasyona basın…",
    "settings.shortcuts.recordingHint": "İptal için Esc · Sıfırlamak için Backspace · Çakışma durumunda yeni bir kombinasyona basın",
    "settings.shortcuts.conflictReserved": "Bu kombinasyon sistem tarafından ayrılmıştır",
    "settings.shortcuts.conflictOccupied": "Zaten \"{command}\" tarafından kullanılıyor",
    "settings.shortcuts.clearConflict": "Varsayılan tuş zaten \"{command}\" tarafından kullanılıyor; geri yüklemek çakışma yaratır. Önce o komutu ayarlayın",
    "settings.shortcuts.stealConfirm": "Yine de yeniden ata (mevcut komut atamasını kaybeder)",
    "settings.shortcuts.invalidNoModifier": "En az bir değiştirici tuş gereklidir (Ctrl / Cmd / Alt)",
    "settings.shortcuts.invalidKey": "Desteklenmeyen tuş",
    "settings.shortcuts.rebindAria": "\"{command}\" için kısayolu yeniden ata",
    "settings.shortcuts.addAria": "\"{command}\" için atama ekle",
    "settings.shortcuts.removeBindingAria": "\"{command}\" için bu atamayı kaldır",
    "settings.shortcuts.duplicateBinding": "Bu komuta zaten atanmış",
    "settings.shortcuts.clearAria": "\"{command}\" için kısayolu temizle",
    "settings.shortcuts.command.newTask": "Yeni Görev",
    "settings.shortcuts.command.composerSend": "Mesajı Gönder",
    "settings.shortcuts.command.composerInsertNewline": "Düzenleyicide Yeni Satır Ekle",
    "settings.shortcuts.command.openWorkspace": "Çalışma Alanını Aç",
    "settings.shortcuts.command.closeActiveContext": "Mevcut Bağlamı Kapat",
    "settings.shortcuts.command.toggleSidebar": "Kenar Çubuğunu Aç/Kapat",
    "settings.shortcuts.command.switchTheme": "Açık/Koyu Temayı Değiştir",
    "settings.shortcuts.command.toggleSidePane": "Yan Paneli Aç/Kapat",
    "settings.shortcuts.command.toggleTerminal": "Terminali Aç/Kapat",
    "settings.shortcuts.command.previousConversation": "Önceki Görev",
    "settings.shortcuts.command.nextConversation": "Sonraki Görev",
    "settings.shortcuts.command.toggleInterfaceMode": "Kodlama/Ofis modunu değiştir",
    "settings.shortcuts.command.openOnboarding": "Başlangıç rehberini aç/kapat",
    "settings.shortcuts.command.navigateBack": "Geriye Git",
    "settings.shortcuts.command.navigateForward": "İleriye Git",
    "settings.shortcuts.command.openModelMenu": "Model Menüsünü Aç",
    "settings.shortcuts.command.cycleSessionMode": "Oturum Modunu Değiştir",
    "settings.shortcuts.command.cycleThoughtLevel": "Düşünce Seviyesini Değiştir",
    "settings.shortcuts.command.findInTask": "Görevde Bul",
    "settings.shortcuts.command.openCommandCenter": "Komut Merkezini Aç",
    "settings.shortcuts.command.openSettings": "Ayarları Aç",
    "settings.shortcuts.command.zoomIn": "Yakınlaştır",
    "settings.shortcuts.command.zoomOut": "Uzaklaştır",
    "settings.shortcuts.command.resetZoom": "Yakınlaştırmayı Sıfırla",
    "settings.modelProvider.startPlan.login": "Giriş Yap",
    "settings.modelProvider.startPlan.status.loginRequired": "Başlangıç Planınızı görüntülemek ve kullanmak için giriş yapın",
    "settings.modelProvider.startPlan.status.expired": "Başlangıç Planının süresi doldu",
    "settings.modelProvider.startPlan.status.noPlan": "Kullanılabilir Başlangıç Planı yok",
    "settings.modelProvider.startPlan.status.loginExpired": "Giriş süreniz doldu. Lütfen tekrar giriş yapın.",
    "settings.modelProvider.codingPlan.status.teamExpired": "Ekip planının süresi doldu. Ekip yöneticinizle iletişime geçin.",
    "settings.plugins.store.category.legal": "Hukuk",
    "settings.workspaceFileSearch.title": "Çalışma Alanı Arama Kapsamı",
    "settings.workspaceFileSearch.description": "Çalışma alanı dosya aramasını kapsayan .zcodeignore kurallarını (gitignore sözdizimi) düzenleyin. Kaydedildikten sonra bir sonraki aramada geçerli olur.",
    "settings.workspaceFileSearch.templateHint": ".zcodeignore henüz mevcut değil: aşağıdaki içerik başlangıç önizlemesidir (.gitignore kopyası + varsayılan hariç tutmalar); yalnızca kaydedildikten sonra çalışma alanına yazılır.",
    "settings.workspaceFileSearch.editorLabel": "Çalışma alanı arama yoksayma kuralları düzenleyicisi",
    "settings.workspaceFileSearch.save": "Kaydet",
    "settings.workspaceFileSearch.saved": "Kaydedildi; bir sonraki aramada geçerli olacak",
    "settings.workspaceFileSearch.saveFailed": "Kaydetme başarısız oldu; günlükleri kontrol edin",
    "settings.workspaceFileSearch.loadFailed": "Yoksayma kuralları yüklenemedi; günlükleri kontrol edin",
    "settings.workspaceFileSearch.resync": ".gitignore dosyasından eşitle",
    "settings.workspaceFileSearch.restoreDefaults": "Varsayılan kuralları geri yükle",
    "settings.workspaceFileSearch.transformFailed": "Bölüm işlemi uygulanamadı; günlükleri kontrol edin",
    "settings.workspaceFileSearch.reveal": "Dosya konumunu göster",
    "settings.workspaceFileSearch.revealHint": "Önce kaydedin; .zcodeignore çalışma alanı kök dizininde bulunur",
    "settings.workspaceFileSearch.unsaved": "Kaydedilmemiş değişiklikler",
    "settings.workspaceFileSearch.noWorkspace": "Açık bir çalışma alanı yok, bu nedenle arama yoksayma kuralları yapılandırılamaz.",
}
