# -*- coding: utf-8 -*-
"""
v314_part3_workflows.py
workflows (105 keys) translations
"""

PART3_TR = {
    "workflows.hub.description": "Açık projelerinizde kayıtlı iş akışları. Bağımsız değişkenleri doldurun ve tekrar çalıştırın.",
    "workflows.hub.sectionTitle": "Kayıtlı iş akışları",
    "workflows.hub.refresh": "Yenile",
    "workflows.hub.createViaChat": "Sohbette oluştur",
    "workflows.hub.group.current": "Geçerli",
    "workflows.hub.global.title": "Genel",
    "workflows.hub.global.hint": "Her projeden görülebilir",
    "workflows.hub.global.empty": "Henüz genel bir iş akışı yok. Derin araştırma gibi belirli bir projeye bağlı olmayan akışlar için uygundur.",
    "workflows.hub.global.unsupported": "Mevcut ajan genel iş akışlarını desteklemiyor.",
    "workflows.hub.global.noLocalRuntime": "Yerel ajana ulaşılamadı; genel iş akışları kullanılamıyor.",
    "workflows.hub.empty.title": "Açık projelerinizde henüz kayıtlı bir iş akışı yok",
    "workflows.hub.empty.hint": "ZCode ile sohbette bir iş akışı tasarlayın, ardından çalıştığında bir projeye kaydetmesini isteyin. Açık olmayan projeler burada görünmez.",
    "workflows.hub.noWorkspace": "İş akışlarını görmek için bir çalışma alanı açın.",
    "workflows.hub.loadError": "İş akışları okunamadı: {error}",
    "workflows.hub.invalid": "{count} dosya okunamadı",
    "workflows.hub.invalidOne": "{count} dosya okunamadı",
    "workflows.hub.card.run": "Çalıştır",
    "workflows.hub.card.menu": "Diğer işlemler",
    "workflows.hub.card.open": "Ayrıntıları görüntüle",
    "workflows.hub.card.revise": "Sohbette düzenle",
    "workflows.hub.card.copyPath": "Yolu kopyala",
    "workflows.hub.card.promoteToGlobal": "Genel düzeye yükselt",
    "workflows.hub.card.moveToProject": "Projeye taşı…",
    "workflows.hub.card.delete": "İş akışını sil",
    "workflows.hub.card.argsMore": "+{count}",
    "workflows.hub.lastRun.never": "Henüz çalıştırılmadı",
    "workflows.hub.lastRun.completed": "Tamamlandı",
    "workflows.hub.lastRun.errored": "Hata verdi",
    "workflows.hub.lastRun.running": "Çalışıyor",
    "workflows.hub.lastRun.stopped": "Durduruldu",
    "workflows.hub.copied": "Yol kopyalandı",
    "workflows.hub.delete.title": "\"{name}\" iş akışı silinsin mi?",
    "workflows.hub.delete.description": "Bu işlem projeden {path} dosyasını kaldırır. Mevcut çalıştırma kayıtları korunur.",
    "workflows.hub.delete.confirm": "Sil",
    "workflows.hub.deleted": "\"{name}\" iş akışı silindi",
    "workflows.hub.deleteFailed": "Silme başarısız oldu: {reason}",
    "workflows.hub.promote.failed": "Genel düzeye yükseltme başarısız oldu: {reason}",
    "workflows.hub.move.toast.project": "{project} konumuna taşındı",
    "workflows.hub.move.targetExists": "Bu ada sahip bir iş akışı orada zaten mevcut",
    "workflows.hub.move.failed": "Taşıma başarısız oldu: {reason}",
    "workflows.hub.moveDialog.title": "Projeye taşı",
    "workflows.hub.moveDialog.noLocalProject": "Bu iş akışını taşımak için yerel bir proje açın",
    "workflows.hub.moveDialog.submit": "Taşı",
    "workflows.hub.launch.title": "{name} Çalıştır",
    "workflows.hub.launch.target": "Çalıştırma konumu",
    "workflows.hub.launch.noLocalProject": "Bu iş akışını çalıştırmak için yerel bir proje açın",
    "workflows.hub.launch.required": "Gerekli",
    "workflows.hub.launch.scope.project": "Proje",
    "workflows.hub.launch.scope.global": "Genel",
    "workflows.hub.launch.note": "{project} içinde yeni bir oturumda hemen başlar",
    "workflows.hub.launch.cancel": "İptal",
    "workflows.hub.launch.submit": "Çalıştır",
    "workflows.hub.launch.error.required": "Gerekli",
    "workflows.hub.launch.error.invalid_number": "Bir sayı olmalıdır",
    "workflows.hub.launch.error.invalid_json": "Geçerli bir JSON değil",
    "workflows.hub.launch.error.invalid_name": "Geçersiz iş akışı adı",
    "workflows.hub.launch.error.not_found": "Bu iş akışı bulunamadı",
    "workflows.hub.launch.error.invalid_args": "Bazı bağımsız değişkenler geçersiz",
    "workflows.hub.launch.error.compile_failed": "İş akışı komut dosyası derlenemedi",
    "workflows.hub.launch.error.session_busy": "Oturum meşgul; tekrar deneyin",
    "workflows.hub.launch.error.start_failed": "İş akışı başlatılamadı",
    "workflows.hub.launch.error.unsupported": "Mevcut ajan iş akışlarını doğrudan çalıştırmayı desteklemiyor",
    "workflows.hub.launch.error.generic": "İş akışı başlatılamadı",
    "workflows.hub.detail.tab.definition": "Tanım",
    "workflows.hub.detail.tab.history": "Çalıştırma geçmişi",
    "workflows.hub.detail.projectColumn": "Proje",
    "workflows.hub.detail.copyPath": "Yolu kopyala",
    "workflows.hub.detail.run": "Çalıştır",
    "workflows.hub.detail.basics": "Temel Bilgiler",
    "workflows.hub.detail.description": "Açıklama",
    "workflows.hub.detail.whenToUse": "Ne zaman kullanılır",
    "workflows.hub.detail.whenToUse.help": "ZCode için yönlendirme ipucu: bu iş akışının ne zaman doğru seçenek olduğu.",
    "workflows.hub.detail.args": "Bağımsız Değişkenler",
    "workflows.hub.detail.args.name": "Ad",
    "workflows.hub.detail.args.type": "Tür",
    "workflows.hub.detail.args.required": "Gerekli",
    "workflows.hub.detail.args.default": "Varsayılan",
    "workflows.hub.detail.args.description": "Açıklama",
    "workflows.hub.detail.args.add": "Bağımsız değişken ekle",
    "workflows.hub.detail.args.remove": "Bağımsız değişkeni kaldır",
    "workflows.hub.detail.args.error.empty_name": "Bağımsız değişkenin bir ada ihtiyacı var",
    "workflows.hub.detail.args.error.duplicate_name": "Yinelenen bağımsız değişken adı",
    "workflows.hub.detail.args.error.invalid_default": "Varsayılan değer türle eşleşmiyor",
    "workflows.hub.detail.meta.note": "Yalnızca dosyanın üstündeki meta veriler değişir; komut dosyası gövdesi olduğu gibi kalır.",
    "workflows.hub.detail.meta.discard": "Değişiklikleri at",
    "workflows.hub.detail.meta.save": "Meta verileri kaydet",
    "workflows.hub.detail.meta.saved": "Meta veriler kaydedildi",
    "workflows.hub.detail.meta.saveFailed": "Kaydetme başarısız oldu: {reason}",
    "workflows.hub.detail.meta.descriptionRequired": "Açıklama gereklidir",
    "workflows.hub.detail.script": "Komut Dosyası",
    "workflows.hub.detail.script.note": "Komut dosyası salt okunurdur. Değiştirmek için sohbette ZCode ile düzenleyin ve yeni bir sürüm kaydedin.",
    "workflows.hub.detail.script.copy": "Komut dosyasını kopyala",
    "workflows.hub.detail.loadError": "Bu iş akışı okunamadı: {reason}",
    "workflows.hub.detail.notFound": "Bu iş akışı artık projede bulunmuyor.",
    "workflows.hub.history.empty": "Henüz çalıştırma yok.",
    "workflows.hub.history.open": "Çalıştırmayı aç",
    "workflows.hub.history.note": "Çalıştırma kayıtları bu projenin iş akışı günlüğünden gelir ve yeniden başlatmalarda korunur. \"Çalıştırmayı aç\", onu başlatan sohbete geri döner ve çalıştırma ayrıntılarını açar.",
    "workflows.hub.history.tokens": "{tokens} token",
    "workflows.hub.artifacts.latest": "En son çıktılar",
    "workflows.hub.reason.invalid_name": "Geçersiz ad",
    "workflows.hub.reason.not_found": "Dosya bulunamadı",
    "workflows.hub.reason.parse_error": "Dosyanın üstündeki meta veriler ayrıştırılamadı",
    "workflows.hub.reason.read_error": "Dosya okunamadı",
    "workflows.hub.time.duration.seconds": "{seconds}sn",
    "workflows.hub.time.duration.minutes": "{minutes}dk {seconds}sn",
}
