# -*- coding: utf-8 -*-
"""
v314_part4_chat_general.py
chat other keys (70 keys) translations
"""

PART4_TR = {
    "chat.officeSuggestions.setting": "Proaktif görev önerileri",
    "chat.officeSuggestions.settingDescription": "Yalnızca Ofis modunda geçerlidir.",
    "chat.plugins.browseMarketplace": "Eklenti mağazasına göz at",
    "chat.plugins.loadError": "Eklentiler yüklenemedi. Tekrar denemek için menüyü yeniden açın.",
    "chat.officeSuggestions.saveError": "Öneri ayarları kaydedilemedi. Lütfen tekrar deneyin.",
    "chat.officeSuggestions.refresh": "Daha fazla göster",
    "chat.officeSuggestions.closeTitle": "Görev önerileri kapatılsın mı?",
    "chat.officeSuggestions.closeDescription": "Bunları Ayarlar'dan tekrar açabilirsiniz.",
    "chat.officeSuggestions.closeError": "Öneriler kapatılamadı. Lütfen tekrar deneyin.",
    "chat.composer.addWorkflow": "İş Akışı",
    "chat.statusPanel.endedWorkflows": "Sona eren iş akışları",
    "chat.empty.greeting.office": "Bugün yapılacaklar listenizde ne var? Bana bırakın.",
    "chat.contextOptimization.started": "Sohbet optimize ediliyor",
    "chat.contextOptimization.skipped": "Sohbet optimizasyonu gerekmiyor",
    "chat.contextOptimization.interrupted": "Sohbet optimizasyonu durduruldu",
    "chat.contextOptimization.failed": "Sohbet optimizasyonu başarısız oldu",
    "chat.contextOptimization.completed": "Sohbet optimize edildi",
    "chat.userInput.epilogue.label": "İş akışı motoru talimatları",
    "chat.composer.backgroundWorks.tooltipWorkflow": "Çalışan iş akışlarını aç",
    "chat.composer.backgroundWorks.tooltipWorkflowDetails": "İş akışı ayrıntılarını aç",
    "chat.statusPanel.workflows": "İş Akışları",
    "chat.toolbar.computerUse.tooltip.idle": "Bilgisayar Kontrolü beklemede — ilk kullanımda otomatik olarak başlayacak",
    "chat.toolbar.thoughtLevel.value.minimal": "Minimum",
    "chat.toolbar.thoughtLevel.value.ultra": "Ultra",
    "chat.workflowLaunch.scope.project": "Proje",
    "chat.workflowLaunch.scope.global": "Genel",
    "chat.workflowLaunch.startedByYou": "İş akışları merkezinden sizin tarafınızdan başlatıldı",
    "chat.workflowLaunch.settingsChangedByYou": "Ayarlar sizin tarafınızdan değiştirildi",
    "chat.workflowLaunch.settings.model": "Alt ajan modeli",
    "chat.workflowLaunch.settings.limit": "Aynı anda en fazla",
    "chat.workflowLaunch.settings.sessionModel": "oturum modeli",
    "chat.workflowLaunch.settings.machineLimit": "bu makinenin sınırı",
    "chat.workflowLaunch.settings.machineLimitValue": "{n} (bu makinenin sınırı)",
    "chat.backgroundResult.workflow.completed": "İş akışı tamamlandı",
    "chat.backgroundResult.workflow.errored": "İş akışı hata verdi",
    "chat.backgroundResult.workflow.stopped": "İş akışı durduruldu",
    "chat.backgroundResult.workflow.stall": "İş akışı modeli bekliyor",
    "chat.backgroundResult.workflow.stall.body": "Bu çalıştırmadaki hiçbir model isteği {minutes} dakikadır başarılı olamadı. Hâlâ çalışıyor ve aralıklarla yeniden deniyor; artık ihtiyacınız yoksa çalıştırma kartından durdurun.",
    "chat.backgroundResult.workflow.stall.reason": "Yeniden deneme nedeni",
    "chat.backgroundResult.workflow.stall.cap": "Mevcut eşzamanlılık",
    "chat.backgroundResult.workflow.waiting": "Alt ajan yanıt bekliyor",
    "chat.backgroundResult.workflow.answered": "Alt ajanın sorusu yanıtlandı",
    "chat.backgroundResult.workflow.asked": "Alt ajan bir soru sordu",
    "chat.backgroundResult.workflow.artifacts.more": "+{count}",
    "chat.permission.responseFailed": "Onay tamamlanamadı. Lütfen tekrar deneyin.",
    "chat.permission.fullAccess": "Tam erişim",
    "chat.permission.fullAccess.description": "Ajana daha fazla onay sormadan tam erişim izni verin.",
    "chat.permission.allowCommand.description": "Bu projedeki eşleşen komutlar için bir daha sorma",
    "chat.permission.allowCommand": "Bu komuta her zaman izin ver",
    "chat.permission.workflow.title": "Bu iş akışı çalıştırılsın mı?",
    "chat.permission.workflow.showScript": "Tam komut dosyasını göster",
    "chat.permission.workflow.hideScript": "Tam komut dosyasını gizle",
    "chat.permission.workflow.refine": "İyileştir",
    "chat.permission.workflow.refine.placeholder": "İş akışının nasıl değişmesi gerektiğini açıklayın…",
    "chat.permission.workflow.allowForSession": "Bu oturumda her zaman izin ver",
    "chat.permission.workflow.allowForSession.description": "Bu oturumdaki iş akışları için bir daha sorma",
    "chat.permission.workflow.amend.title": "Bu iş akışı düzeltilsin mi?",
    "chat.permission.workflow.amends": "Düzeltmeler çalıştırması",
    "chat.permission.workflow.amends.running": "hâlâ çalışıyor, durdurulacak",
    "chat.permission.workflow.amends.scriptUnchanged": "komut dosyası değişmedi",
    "chat.permission.workflow.maxConcurrency": "Aynı anda en fazla {count} alt ajan",
    "chat.permission.workflow.subagentModel": "Alt ajanlar {model} üzerinde çalışır",
    "chat.permission.workflow.saved.badge": "Kayıtlı iş akışı",
    "chat.permission.workflow.saved.scope.project": "proje",
    "chat.permission.workflow.saved.args": "Bağımsız Değişkenler",
    "chat.permission.workflow.save.title": "Bu iş akışı projeye kaydedilsin mi?",
    "chat.permission.workflow.save.overwriteTitle": "Mevcut kayıtlı iş akışının üzerine yazılsın mı?",
    "chat.permission.workflow.save.overwriteHint": "Bu yolda bu ada sahip bir iş akışı zaten var. Kaydetmek tüm dosyanın yerini alır.",
    "chat.permission.workflow.save.path": "Yol",
    "chat.permission.workflow.save.description": "Açıklama",
    "chat.permission.workflow.save.whenToUse": "Ne zaman kullanılır",
    "chat.permission.workflow.save.args": "Bağımsız Değişkenler",
    "chat.permission.workflow.save.args.name": "Ad",
    "chat.permission.workflow.save.args.type": "Tür",
    "chat.permission.workflow.save.args.required": "Gerekli",
    "chat.permission.workflow.save.args.requiredYes": "Gerekli",
    "chat.permission.workflow.save.args.requiredNo": "İsteğe Bağlı",
    "chat.permission.workflow.save.args.default": "Varsayılan",
}
